# print(5+6)
# print(5-6)
# print(5*6)
# print(5/6)
# print(5%6)
# print(5**6)

n1=int(input("entr the value for n1:"))
n2=int(input("enter the value for n2:"))
print("the addition of n1 and n2:",n1+n2)
print("the subtraction of n1 and n2:",n1-n2)
print("the multiplication of n1 and n2:",n1*n2)
print("the divison of n1 and n2:",n1/n2)
print("the power of n1 and n2:",n1**n2)
print("the modulus of two numbers is:",n1%n2)
