a="!arry bhai !!!!"
print(len(a))
print(a.upper())
print(a.lower())
a1=a.upper()
print(a1)
print(a.strip("!"))
print(a.rstrip("!"))
print(a.lstrip("!"))
print(a.replace("!arry bhai !!!","hari hema"))
print(a.split())
a1="lockhading towards itpl"
print(a1.capitalize())
print(a1.title())
print(a1.center(50))
print(a.count("a"))
print(a1.endswith("Itpl"))
print(a1.find("lockheading"))
print(a1.isalnum())
print(a1.isalpha())
a2="       "
print(a2.isspace())
